In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [10]:
plots_1 = pd.read_csv(
    "https://raw.githubusercontent.com/nickeubank/practicaldatascience_book/main/notebooks/class_5/week_1/data/basic_plotting_datasets/datasaurus_1.txt",
    delimiter="\t",
)
plots_1.head()

   Unnamed: 0      x_var      y_var
0           0  32.331110  61.411101
1           1  53.421463  26.186880
2           2  63.920202  30.832194
3           3  70.289506  82.533649
4           4  34.118830  45.734551

In [ ]:
# calc/print summary statistics for datasets
title = {}
for i in range(1, 14):
    title[i] = f"Datasaurus {i}"
    print(title[i])
    plot = pd.read_csv(
        f"https://raw.githubusercontent.com/nickeubank/practicaldatascience_book/main/notebooks/class_5/week_1/data/basic_plotting_datasets/datasaurus_{i}.txt",
        sep=r"\s+",
    )
    print(plot.describe())

Datasaurus 1
            x_var       y_var
count  142.000000  142.000000
mean    54.266100   47.834721
std     16.769825   26.939743
min     15.560750    0.015119
25%     39.724115   24.625892
50%     53.340296   47.535269
75%     69.146597   71.803148
max     91.639961   97.475771
Datasaurus 2
            x_var       y_var
count  142.000000  142.000000
mean    54.268730   47.830823
std     16.769239   26.935727
min     19.288205    9.691547
25%     41.627968   26.244735
50%     53.842088   47.382937
75%     64.798900   72.532852
max     91.735539   85.876229
Datasaurus 3
            x_var       y_var
count  142.000000  142.000000
mean    54.267320   47.837717
std     16.760013   26.930036
min     21.863581   16.326546
25%     43.379116   18.349610
50%     54.023213   51.025022
75%     64.972672   77.782382
max     85.664761   85.578134
Datasaurus 4
            x_var       y_var
count  142.000000  142.000000
mean    54.263273   47.832253
std     16.765142   26.935403
min     22.307700    2.948700
25%     44.102600   25.288450
50%     53.333300   46.025600
75%     64.743600   68.525675
max     98.205100   99.487200
Datasaurus 5
            x_var       y_var
count  142.000000  142.000000
mean    54.260303   47.839829
std     16.767735   26.930192
min     25.443526   15.771892
25%     50.359707   17.107141
50%     50.976768   51.299291
75%     75.197363   82.881589
max     77.954435   94.249328
Datasaurus 6
            x_var       y_var
count  142.000000  142.000000
mean    54.261442   47.830252
std     16.765898   26.939876
min     22.003709   10.463915
25%     42.293828   30.479911
50%     53.069678   50.473527
75%     66.768274   70.349471
max     98.288123   90.458936
Datasaurus 7
            x_var       y_var
count  142.000000  142.000000
mean    54.268805   47.835450
std     16.766704   26.939998
min     17.893499   14.913962
25%     41.535981   22.920843
50%     54.168689   32.499203
75%     63.952667   75.940022
max     96.080519   87.152208
Datasaurus 8
            x_var       y_var
count  142.000000  142.000000
mean    54.267849   47.835896
std     16.766759   26.936105
min     18.109472    0.303872
25%     42.890931   27.840858
50%     53.135159   46.401314
75%     64.469989   68.439430
max     95.593416   99.644179
Datasaurus 9
            x_var       y_var
count  142.000000  142.000000
mean    54.265882   47.831496
std     16.768853   26.938608
min     20.209778    5.645777
25%     42.810866   24.756248
50%     54.261345   45.292238
75%     64.488010   70.855844
max     95.260528   99.579591
Datasaurus 10
            x_var       y_var
count  142.000000  142.000000
mean    54.267341   47.839545
std     16.768959   26.930275
min     27.024603   14.365590
25%     41.034210   20.374135
50%     56.534732   50.110554
75%     68.711493   63.548584
max     86.435897   92.214989
Datasaurus 11
            x_var       y_var
count  142.000000  142.000000
mean    54.269927   47.836988
std     16.769959   26.937684
min     30.449654    2.734760
25%     49.964506   22.752884
50%     50.362890   47.113616
75%     69.504068   65.845391
max     89.504851   99.694680
Datasaurus 12
            x_var       y_var
count  142.000000  142.000000
mean    54.266916   47.831602
std     16.770000   26.937902
min     27.439632    0.217006
25%     35.522449   24.346941
50%     64.550226   46.279331
75%     67.453672   67.568127
max     77.915874   99.283764
Datasaurus 13
            x_var       y_var
count  142.000000  142.000000
mean    54.260150   47.839717
std     16.769958   26.930002
min     31.106867    4.577661
25%     40.091656   23.470809
50%     47.136458   39.876211
75%     71.856923   73.609634
max     85.446186   97.837615

# Exercise 1

Load the first dataset and get a feel for the data.

Note that the file being downloaded is not actually a CSV file. It is tab-delimited, meaning that within each row, columns are separated by tabs rather than commas. We communicate this to pandas with the `delimiter="\t"` option (`"\t"` is how we write a tab, as we will discuss in future lessons).

In [11]:
file_1 = pd.read_csv(
    "https://raw.githubusercontent.com/nickeubank/practicaldatascience_book/main/notebooks/class_5/week_1/data/basic_plotting_datasets/datasaurus_1.txt",
    delimiter="\t",
)
file_1.head()

   Unnamed: 0      x_var      y_var
0           0  32.331110  61.411101
1           1  53.421463  26.186880
2           2  63.920202  30.832194
3           3  70.289506  82.533649
4           4  34.118830  45.734551

# Exercise 2

In order to get a better sense of what these datasets look like, write a loop that iterates over each example dataset (numbered 1 to 13) and print out the mean and standard deviation for `x_var` and `y_var` and their correlation for each dataset.

For example, the first iteration of this loop might return something like:

 ```python
Example Dataset 1: 
Mean x: 23.12321978429576, 
Mean y: 98.23980921730972, 
Std Dev x: 21.2389710287, 
Std Dev y: 32.2389081209832,
Correlation: 0.73892819281
```

(Though you shouldn’t get those specific values. You might get values that are quite similar across datasets.)

Hint: When writing this type of code, it is often best to start by writing code to do what you want for the first iteration of the loop. Or, as Drew and Genevieve would say, WORK ONE CASE BY HAND! Once you have code that works for the first example dataset, then write the full loop around it.

In [23]:
# copying what Nick does
df = pd.read_csv(
    "https://raw.githubusercontent.com/nickeubank/practicaldatascience_book"
    "/main/notebooks/class_5/week_1/data/basic_plotting_datasets/datasaurus_1.txt",
    delimiter="\t",
)

for i in range(1, 14):
    url = (
        "https://raw.githubusercontent.com/nickeubank/practicaldatascience_book"
        f"/main/notebooks/class_5/week_1/data/basic_plotting_datasets/datasaurus_{i}.txt"
    )

    df = pd.read_csv(url, delimiter="\t")

    print(f"Example Dataset {i}:")
    print(f"Mean x: {df['x_var'].mean():.3f},")
    print(f"Mean y: {df['y_var'].mean():.3f},")
    print(f"Std Dev x: {df['x_var'].std():.3f},")
    print(f"Std Dev y: {df['y_var'].std():.3f},")
    print(f"Correlation: {df[['y_var','x_var']].corr().iloc[0, 1]:.3f}")

Example Dataset 1:
Mean x: 54.266,
Mean y: 47.835,
Std Dev x: 16.770,
Std Dev y: 26.940,
Correlation: -0.064
Example Dataset 2:
Mean x: 54.269,
Mean y: 47.831,
Std Dev x: 16.769,
Std Dev y: 26.936,
Correlation: -0.069
Example Dataset 3:
Mean x: 54.267,
Mean y: 47.838,
Std Dev x: 16.760,
Std Dev y: 26.930,
Correlation: -0.068
Example Dataset 4:
Mean x: 54.263,
Mean y: 47.832,
Std Dev x: 16.765,
Std Dev y: 26.935,
Correlation: -0.064
Example Dataset 5:
Mean x: 54.260,
Mean y: 47.840,
Std Dev x: 16.768,
Std Dev y: 26.930,
Correlation: -0.060
Example Dataset 6:
Mean x: 54.261,
Mean y: 47.830,
Std Dev x: 16.766,
Std Dev y: 26.940,
Correlation: -0.062
Example Dataset 7:
Mean x: 54.269,
Mean y: 47.835,
Std Dev x: 16.767,
Std Dev y: 26.940,
Correlation: -0.069
Example Dataset 8:
Mean x: 54.268,
Mean y: 47.836,
Std Dev x: 16.767,
Std Dev y: 26.936,
Correlation: -0.069
Example Dataset 9:
Mean x: 54.266,
Mean y: 47.831,
Std Dev x: 16.769,
Std Dev y: 26.939,
Correlation: -0.069
Example Dataset 10:
Mean x: 54.267,
Mean y: 47.840,
Std Dev x: 16.769,
Std Dev y: 26.930,
Correlation: -0.063
Example Dataset 11:
Mean x: 54.270,
Mean y: 47.837,
Std Dev x: 16.770,
Std Dev y: 26.938,
Correlation: -0.069
Example Dataset 12:
Mean x: 54.267,
Mean y: 47.832,
Std Dev x: 16.770,
Std Dev y: 26.938,
Correlation: -0.067
Example Dataset 13:
Mean x: 54.260,
Mean y: 47.840,
Std Dev x: 16.770,
Std Dev y: 26.930,
Correlation: -0.066

# Exercise 3

Based only on these results, discuss what might you conclude about these example datasets with your partner. Write down your thoughts.

> They are fairly similar

# Exercise 4

Write a loop that iterates over these example datasets and plots a simple scatter plot of each dataset with the `x` variable on the x-axis and the `y` variable on the y-axis.

# Exercise 5
Review you plots. How does your impression of how these datasets differ from what you wrote down in Exercise 3?

# Economic Development and… Your Choice!
## Exercise 6

Load the World Development Indicator data [here](https://raw.githubusercontent.com/nickeubank/practicaldatascience/master/Example_Data/wdi_plotting.csv)

Rather than picking a single year, pick a single country and look at how GDP per capita and one of the other variables in that dataset have evolved together over time. For now, plot the two series them as two separate plots. Be sure your figure includes a title and x and y-axis labels in plain English (not variable names).

Make any adjustments to the functional forms of your variables and/or axes needed to make the figure legible.

## Exercise 7

Let’s put the two series together so that they share a common x-axis of (so both series are plotted in the same plot, and the y-axes is time. Obviously your different series will need different y-axes).

Use your detective skills (and some guess and check work) to figure out how to get it to work!

## Exercise 8

LLMs are *great* for plotting, and they’re really good at matplotlib (it’s been around forever, so there’s lots of training data). Using Github Copilot Chat in VS Code, made the following changes to your plot:

- Add a note to the bottom of the plot in the bottom left that reports the source for your data.
- Change the x-axes so that it prints out the year every 5 years (1990, 1995, 2000, etc.).
- Add a red, dashed, vertical line at the year 2000.
- Add text that is rotated 90 degrees, in red, alongside that vertical line in the middle of the plot that says “New Millenium.”